version: "3.8"

services:

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    networks:
      - net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=simple

  backend:
    build: ./backend
    restart: always
    container_name: back
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=simple
      - POSTGRES_HOST=db
    networks:
      - net
      
  frontend:
    build: ./frontend
    restart: always
    container_name: front
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - net

volumes:
  postgres-data:

networks:
  net:
    name: net
